name: FlagGame
version: ${project.version}
main: net.kunmc.lab.flaggame.FlagGame
api-version: 1.15
commands:
  flag:
    description: flagGame.
    usage: /<command> [start] [player]
    permission: op
